# Generated by Django 6.0.6 on 2026-06-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='last_daily_bonus_claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('bonus', 'Bonus'), ('daily_bonus', 'Daily Bonus'), ('bet', 'Bet'), ('win', 'Win'), ('refund', 'Refund')], max_length=20),
        ),
    ]
