# Generated by Django 6.0.6 on 2026-06-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='client_seed',
            field=models.CharField(default='legacy-client-seed', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='nonce',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bet',
            name='server_seed',
            field=models.CharField(default='legacy-server-seed', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='server_seed_hash',
            field=models.CharField(default='legacy-server-seed-hash', max_length=128),
            preserve_default=False,
        ),
    ]
