# Generated by Django 6.0.6 on 2026-06-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_bet_client_seed_bet_nonce_bet_server_seed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='game_type',
            field=models.CharField(choices=[('coinflip', 'Coinflip'), ('roulette', 'Roulette'), ('case_opening', 'Case Opening')], default='coinflip', max_length=30),
        ),
        migrations.AddField(
            model_name='bet',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='bet',
            name='choice',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bet',
            name='result',
            field=models.CharField(max_length=100),
        ),
    ]
