# Generated by Django 6.0.6 on 2026-06-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_case_caseitem_inventoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseitem',
            name='image_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
